#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generatore per una singola sottocategoria di esercizi.

Uso:
    python generate_exercises.py fisica/meccanica/dinamica
    python generate_exercises.py fisica/elettrostatica/coulomb
    python generate_exercises.py matematica/limiti/forme-indeterminate

L'argomento e' sempre un percorso relativo alla root del sito e deve iniziare
con fisica/ oppure matematica/.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from html import escape, unescape
from pathlib import Path, PurePosixPath
from typing import Any


ALLOWED_ROOTS = {"fisica", "matematica"}
DEFAULT_JSON_NAME = "exercises.json"
GLOBAL_CATALOG_NAME = "esercizi.json"
GENERATED_INDEX_MARKER = "Generated by generate_exercises.py"
EXCLUDED_HTML_NAMES = {"index.html"}
EXCLUDED_NAME_PARTS = ("template", "modello")
SUBJECTS = {
    "fisica": {
        "name": "Fisica",
        "order": 1,
        "color": "#5bd4c4",
        "description": "Esercizi di fisica organizzati per ambito.",
    },
    "matematica": {
        "name": "Matematica",
        "order": 2,
        "color": "#8ab4f0",
        "description": "Esercizi di matematica organizzati per argomento.",
    },
}


def slug_to_title(slug: str) -> str:
    words = re.split(r"[-_]+", slug.strip())
    return " ".join(word.capitalize() for word in words if word)


def natural_key(value: str) -> list[Any]:
    return [
        int(part) if part.isdigit() else part.casefold()
        for part in re.split(r"(\d+)", value)
    ]


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError:
        return path.read_text(encoding="cp1252")


def write_text_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        current = read_text(path)
        if current == content:
            return False
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def normalize_target(raw_target: str) -> PurePosixPath:
    target = raw_target.strip().replace("\\", "/")
    while target.startswith("./"):
        target = target[2:]

    if not target:
        raise ValueError("Devi indicare una sottocategoria.")

    if Path(target).is_absolute() or re.match(r"^[A-Za-z]:", target):
        raise ValueError("Il percorso deve essere relativo alla root del sito.")

    parts = [part for part in PurePosixPath(target).parts if part not in ("", ".")]

    if len(parts) < 2:
        raise ValueError("Il percorso deve iniziare con fisica/... oppure matematica/...")

    if parts[0] not in ALLOWED_ROOTS:
        raise ValueError("Il percorso deve iniziare con fisica/ oppure matematica/.")

    if any(part == ".." for part in parts):
        raise ValueError("Il percorso non puo' contenere '..'.")

    return PurePosixPath(*parts)


def load_json(path: Path) -> dict[str, Any] | None:
    try:
        data = json.loads(read_text(path))
    except (OSError, json.JSONDecodeError):
        return None
    return data if isinstance(data, dict) else None


def is_exercise_manifest(path: Path) -> bool:
    data = load_json(path)
    if not data:
        return False
    if "categories" in data:
        return False
    return isinstance(data.get("exercises"), list)


def find_manifest_path(target_dir: Path, forced_name: str | None) -> Path:
    if forced_name:
        return target_dir / forced_name

    preferred_names = (
        f"{target_dir.name}.json",
        DEFAULT_JSON_NAME,
    )

    for name in preferred_names:
        candidate = target_dir / name
        if candidate.exists() and is_exercise_manifest(candidate):
            return candidate

    candidates = [
        path
        for path in sorted(target_dir.glob("*.json"), key=lambda p: natural_key(p.name))
        if is_exercise_manifest(path)
    ]

    if candidates:
        return candidates[0]

    return target_dir / DEFAULT_JSON_NAME


def load_collection_config(target_dir: Path) -> dict[str, Any]:
    config_path = target_dir / "collection.json"
    data = load_json(config_path) if config_path.exists() else None
    return data or {}


def contains_html_files(path: Path) -> bool:
    return path.exists() and path.is_dir() and any(path.glob("*.html"))


def resolve_source_dir(target_dir: Path, collection_config: dict[str, Any], manifest_path: Path) -> Path:
    sources_dir = collection_config.get("sourcesDir")
    if isinstance(sources_dir, str) and sources_dir.strip():
        return target_dir / sources_dir

    existing_manifest = load_json(manifest_path) if manifest_path.exists() else None
    manifest_sources_dir = existing_manifest.get("sourceDir") if existing_manifest else None
    if isinstance(manifest_sources_dir, str) and manifest_sources_dir.strip() and manifest_sources_dir != ".":
        return target_dir / manifest_sources_dir

    fallback_dir = target_dir / "esercizi"
    if contains_html_files(fallback_dir):
        return fallback_dir

    return target_dir


def looks_like_exercise_filename(path: Path) -> bool:
    name = path.name.casefold()
    stem = path.stem.casefold()
    return bool(
        re.match(r"^es[-_]?\d+(?:[-_].*)?\.html?$", name)
        or re.match(r"^\d+[-_].+\.html?$", name)
        or re.search(r"(?:^|[-_])\d+(?:[-_]|$)", stem)
    )


def looks_like_exercise_html(path: Path, html: str) -> bool:
    lower_name = path.name.casefold()
    if lower_name in EXCLUDED_HTML_NAMES:
        return False

    stem = path.stem.casefold()
    if any(part in stem for part in EXCLUDED_NAME_PARTS):
        return False

    if looks_like_exercise_filename(path):
        return True

    markers = (
        "EXERCISE_METADATA",
        "exercise-metadata",
        "data-exercise-statement",
        "data-exercise-solution",
        "EXERCISE_CONTENT_START",
        "exercise-card",
        "exercise-problem",
        "exercise-solution",
    )

    if any(marker in html for marker in markers):
        return True

    return bool(re.search(r"<article\b[^>]*class=[\"'][^\"']*exercise", html, re.I))


def discover_exercise_files(source_dir: Path) -> tuple[list[Path], list[tuple[Path, str]]]:
    if not source_dir.exists():
        raise FileNotFoundError(f"La cartella sorgente non esiste: {source_dir}")
    if not source_dir.is_dir():
        raise NotADirectoryError(f"Il percorso sorgente non e' una cartella: {source_dir}")

    exercise_files: list[Path] = []
    skipped: list[tuple[Path, str]] = []

    for path in sorted(source_dir.glob("*.html"), key=lambda p: natural_key(p.name)):
        if path.name.casefold() in EXCLUDED_HTML_NAMES:
            skipped.append((path, "index.html"))
            continue

        if any(part in path.stem.casefold() for part in EXCLUDED_NAME_PARTS):
            skipped.append((path, "template/modello"))
            continue

        html = read_text(path)
        if looks_like_exercise_html(path, html):
            exercise_files.append(path)
        else:
            skipped.append((path, "non sembra un esercizio"))

    return exercise_files, skipped


def strip_html(html: str) -> str:
    cleaned = re.sub(r"<(script|style|template)\b.*?</\1>", " ", html, flags=re.I | re.S)
    cleaned = re.sub(r"<[^>]+>", " ", cleaned)
    cleaned = unescape(cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned)
    return cleaned.strip()


def shorten(text: str, limit: int = 180) -> str:
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "..."


def extract_title(html: str) -> str | None:
    for tag in ("h1", "h2", "title"):
        match = re.search(rf"<{tag}\b[^>]*>(.*?)</{tag}>", html, flags=re.I | re.S)
        if match:
            text = strip_html(match.group(1))
            if text:
                return text
    return None


def extract_meta_description(html: str) -> str | None:
    pattern = re.compile(
        r"<meta\b(?=[^>]*\bname=[\"']description[\"'])(?=[^>]*\bcontent=[\"']([^\"']+)[\"'])[^>]*>",
        flags=re.I | re.S,
    )
    match = pattern.search(html)
    if match:
        text = unescape(match.group(1)).strip()
        return shorten(text) if text else None
    return None


def extract_short_description(html: str) -> str | None:
    candidates = [
        r"<template\b[^>]*data-exercise-statement[^>]*>(.*?)</template>",
        r"<(?:div|section)\b[^>]*class=[\"'][^\"']*(?:problem-text|problem)[^\"']*[\"'][^>]*>(.*?)</(?:div|section)>",
        r"<p\b[^>]*class=[\"'][^\"']*(?:problem-text|problem)[^\"']*[\"'][^>]*>(.*?)</p>",
        r"<p\b[^>]*>(.*?)</p>",
    ]

    for pattern in candidates:
        match = re.search(pattern, html, flags=re.I | re.S)
        if match:
            text = strip_html(match.group(1))
            if text:
                return shorten(text)

    return None


def strip_js_comments(raw: str) -> str:
    result: list[str] = []
    in_string: str | None = None
    escaped = False
    i = 0

    while i < len(raw):
        char = raw[i]
        nxt = raw[i + 1] if i + 1 < len(raw) else ""

        if in_string:
            result.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == in_string:
                in_string = None
            i += 1
            continue

        if char in ("'", '"'):
            in_string = char
            result.append(char)
            i += 1
            continue

        if char == "/" and nxt == "/":
            i += 2
            while i < len(raw) and raw[i] not in "\r\n":
                i += 1
            continue

        if char == "/" and nxt == "*":
            i += 2
            while i + 1 < len(raw) and not (raw[i] == "*" and raw[i + 1] == "/"):
                i += 1
            i += 2
            continue

        result.append(char)
        i += 1

    return "".join(result)


def quote_unquoted_keys(raw: str) -> str:
    return re.sub(
        r"([{,]\s*)([A-Za-z_$][\w$]*)\s*:",
        lambda match: f'{match.group(1)}"{match.group(2)}":',
        raw,
    )


def remove_trailing_commas(raw: str) -> str:
    return re.sub(r",(\s*[}\]])", r"\1", raw)


def parse_json_like(raw: str) -> dict[str, Any]:
    cleaned = remove_trailing_commas(strip_js_comments(raw.strip()))

    try:
        data = json.loads(cleaned)
        if isinstance(data, dict):
            return data
    except json.JSONDecodeError:
        pass

    jsonish = remove_trailing_commas(quote_unquoted_keys(cleaned))

    try:
        data = json.loads(jsonish)
        if isinstance(data, dict):
            return data
    except json.JSONDecodeError:
        pass

    pythonish = re.sub(r"\btrue\b", "True", jsonish, flags=re.I)
    pythonish = re.sub(r"\bfalse\b", "False", pythonish, flags=re.I)
    pythonish = re.sub(r"\bnull\b", "None", pythonish, flags=re.I)

    data = ast.literal_eval(pythonish)
    if not isinstance(data, dict):
        raise ValueError("Il blocco metadati non contiene un oggetto.")
    return data


def find_balanced_object(text: str, start: int) -> str | None:
    if start < 0 or start >= len(text) or text[start] != "{":
        return None

    depth = 0
    in_string: str | None = None
    escaped = False

    for index in range(start, len(text)):
        char = text[index]

        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == in_string:
                in_string = None
            continue

        if char in ("'", '"'):
            in_string = char
            continue

        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[start : index + 1]

    return None


def extract_script_metadata(html: str, filename: str, strict: bool) -> tuple[dict[str, Any], str | None]:
    script_pattern = re.compile(
        r"<script\b(?P<attrs>[^>]*)>(?P<body>.*?)</script>",
        flags=re.I | re.S,
    )

    for match in script_pattern.finditer(html):
        attrs = match.group("attrs")
        body = match.group("body").strip()
        if "exercise-metadata" not in attrs.casefold():
            continue

        try:
            return parse_json_like(body), "metadata"
        except Exception as exc:
            message = f"Metadati non validi in {filename}: {exc}"
            if strict:
                raise ValueError(message) from exc
            print(f"[AVVISO] {message}")
            return {}, None

    marker = "window.EXERCISE_METADATA"
    marker_pos = html.find(marker)
    if marker_pos >= 0:
        assignment_pos = html.find("=", marker_pos)
        brace_pos = html.find("{", assignment_pos)
        raw_object = find_balanced_object(html, brace_pos)

        if raw_object:
            try:
                return parse_json_like(raw_object), "metadata"
            except Exception as exc:
                message = f"Metadati window.EXERCISE_METADATA non validi in {filename}: {exc}"
                if strict:
                    raise ValueError(message) from exc
                print(f"[AVVISO] {message}")
                return {}, None

    if strict:
        raise ValueError(f"Nessun blocco metadati trovato in {filename}")

    return {}, None


def first_number(value: str) -> int | None:
    match = re.search(r"\d+", value)
    return int(match.group(0)) if match else None


def normalize_order(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, str) and value.strip().isdigit():
        return int(value.strip())
    return None


def infer_path_metadata(relative_path: PurePosixPath) -> dict[str, str]:
    parts = relative_path.parts
    subject = slug_to_title(parts[0]) if parts else ""
    category = slug_to_title(parts[1]) if len(parts) > 1 else subject
    topic = slug_to_title(parts[-1]) if parts else ""
    return {
        "subject": subject,
        "category": category,
        "topic": topic,
        "title": topic or category or subject,
    }


def extract_metadata(
    html: str,
    file_path: Path,
    rel_file: str,
    category_rel: PurePosixPath,
    strict: bool,
) -> dict[str, Any]:
    data, source_format = extract_script_metadata(html, file_path.name, strict=strict)
    inferred = infer_path_metadata(category_rel)

    title = (
        data.get("title")
        or extract_title(html)
        or slug_to_title(file_path.stem)
    )

    description = (
        data.get("description")
        or extract_meta_description(html)
        or extract_short_description(html)
    )

    order = normalize_order(data.get("order"))
    if order is None:
        order = first_number(file_path.stem)

    exercise: dict[str, Any] = dict(data)
    exercise.setdefault("id", file_path.stem)
    exercise["title"] = str(title)
    if description:
        exercise["description"] = str(description)
    exercise.setdefault("subject", inferred["subject"])
    exercise.setdefault("category", inferred["category"])
    exercise.setdefault("topic", inferred["topic"])
    exercise.setdefault("tags", [])
    exercise["order"] = order
    exercise["file"] = rel_file
    exercise["source"] = rel_file
    exercise["sourceFormat"] = source_format or "inferred"
    return exercise


def exercise_sort_key(exercise: dict[str, Any]) -> tuple[int, Any]:
    order = normalize_order(exercise.get("order"))
    if order is not None:
        return (0, order)
    return (1, natural_key(str(exercise.get("file") or exercise.get("source") or "")))


def unique_list(values: list[Any], limit: int | None = None) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []

    for value in values:
        if value is None:
            continue

        items = value if isinstance(value, list) else [value]
        for item in items:
            text = str(item).strip()
            key = text.casefold()
            if not text or key in seen:
                continue
            seen.add(key)
            result.append(text)
            if limit is not None and len(result) >= limit:
                return result

    return result


def first_existing_value(*values: Any) -> Any:
    for value in values:
        if value not in (None, "", []):
            return value
    return None


def build_manifest(
    target_dir: Path,
    source_dir: Path,
    category_rel: PurePosixPath,
    manifest_path: Path,
    collection_config: dict[str, Any],
    strict: bool,
) -> dict[str, Any]:
    existing = load_json(manifest_path) if manifest_path.exists() else None
    path_meta = infer_path_metadata(category_rel)

    exercise_files, skipped = discover_exercise_files(source_dir)
    if skipped:
        for path, reason in skipped:
            print(f"[INFO] HTML ignorato ({reason}): {path.name}")

    exercises: list[dict[str, Any]] = []
    for path in exercise_files:
        html = read_text(path)
        rel_file = path.relative_to(target_dir).as_posix()
        exercises.append(
            extract_metadata(
                html=html,
                file_path=path,
                rel_file=rel_file,
                category_rel=category_rel,
                strict=strict,
            )
        )

    exercises.sort(key=exercise_sort_key)
    for index, exercise in enumerate(exercises, start=1):
        if normalize_order(exercise.get("order")) is None:
            exercise["order"] = index

    manifest: dict[str, Any] = dict(existing or {})
    manifest.update(
        {
            "generator": "generate_exercises.py",
            "title": manifest.get("title")
            or collection_config.get("title")
            or path_meta["title"],
            "subject": manifest.get("subject")
            or collection_config.get("subject")
            or path_meta["subject"],
            "category": manifest.get("category")
            or collection_config.get("category")
            or path_meta["category"],
            "topic": manifest.get("topic")
            or collection_config.get("topic")
            or path_meta["topic"],
            "description": manifest.get("description")
            or collection_config.get("description")
            or f"Raccolta di esercizi svolti: {len(exercises)} esercizi con testo e soluzione espandibile.",
            "icon": first_existing_value(
                manifest.get("icon"),
                collection_config.get("icon"),
                *(exercise.get("icon") for exercise in exercises),
            ),
            "order": first_existing_value(
                normalize_order(manifest.get("order")),
                normalize_order(collection_config.get("order")),
            ),
            "tags": unique_list(
                [
                    manifest.get("tags"),
                    collection_config.get("tags"),
                    *(exercise.get("tags") for exercise in exercises),
                ],
                limit=12,
            ),
            "level": first_existing_value(
                manifest.get("level"),
                collection_config.get("level"),
                *(exercise.get("level") for exercise in exercises),
            ),
            "schoolYear": first_existing_value(
                manifest.get("schoolYear"),
                collection_config.get("schoolYear"),
                *(exercise.get("schoolYear") for exercise in exercises),
            ),
            "estimatedTime": first_existing_value(
                manifest.get("estimatedTime"),
                collection_config.get("estimatedTime"),
            ),
            "isWip": bool(first_existing_value(manifest.get("isWip"), collection_config.get("isWip"), False)),
            "path": category_rel.as_posix(),
            "sourceDir": source_dir.relative_to(target_dir).as_posix()
            if source_dir != target_dir
            else ".",
            "count": len(exercises),
            "exercises": exercises,
        }
    )

    return manifest


def json_dump(data: dict[str, Any]) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def html_text(value: Any) -> str:
    return escape(str(value), quote=False)


def relative_root_link(category_rel: PurePosixPath) -> str:
    return "../" * len(category_rel.parts) + "index.html"


def build_index_html(manifest: dict[str, Any], json_name: str, category_rel: PurePosixPath) -> str:
    title = str(manifest.get("title") or slug_to_title(category_rel.name))
    subject = str(manifest.get("subject") or slug_to_title(category_rel.parts[0]))
    category = str(manifest.get("category") or "")
    topic = str(manifest.get("topic") or title)
    description = str(
        manifest.get("description")
        or "Raccolta di esercizi svolti con testo e soluzione espandibile."
    )
    count = int(manifest.get("count") or 0)
    subtitle_parts = [part for part in (subject, category, topic) if part]
    subtitle = " &middot; ".join(html_text(part) for part in subtitle_parts)
    back_link = relative_root_link(category_rel)

    return f"""<!DOCTYPE html>
<html lang="it">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html_text(title)} | Esercizi svolti</title>
<!-- {GENERATED_INDEX_MARKER}. Source files stay separate and are loaded at runtime. -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;1,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js"></script>
<style>
  :root {{
    --cream: #f5f0e8;
    --cream-dark: #ede5d5;
    --ink: #1a1612;
    --ink-light: #3d3530;
    --ink-faint: #7a6f65;
    --accent: #8b3a2a;
    --accent-warm: #b5622a;
    --gold: #c9a84c;
    --border: #c8b89a;
    --border-light: #ddd0bc;
    --blue-muted: #3a5a7a;
    --green-muted: #3a6a4a;
    --shadow: rgba(26,22,18,0.12);
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--cream); color: var(--ink); font-family: 'IBM Plex Sans', sans-serif; font-size: 16px; line-height: 1.7; }}
  .site-header {{ background: var(--ink); color: var(--cream); padding: 3rem 2rem 2.5rem; text-align: center; position: relative; overflow: hidden; }}
  .site-header::before {{ content: ''; position: absolute; inset: 0; background: repeating-linear-gradient(-45deg,transparent,transparent 40px,rgba(255,255,255,0.015) 40px,rgba(255,255,255,0.015) 41px); }}
  .site-header h1 {{ font-family: 'EB Garamond', serif; font-size: clamp(2.2rem, 5vw, 3.4rem); font-weight: 500; letter-spacing: 0.02em; position: relative; }}
  .site-header .subtitle {{ font-family: 'IBM Plex Mono', monospace; font-size: 0.78rem; color: var(--gold); margin-top: 0.5rem; letter-spacing: 0.12em; text-transform: uppercase; position: relative; }}
  .site-header .meta-row {{ display: flex; justify-content: center; gap: 0.8rem; flex-wrap: wrap; margin-top: 1.2rem; font-size: 0.82rem; color: rgba(245,240,232,0.6); position: relative; }}
  .back-link {{ color: rgba(245,240,232,0.7); font-family: 'IBM Plex Mono', monospace; font-size: 0.72rem; letter-spacing: 0.08em; text-decoration: none; text-transform: uppercase; position: relative; }}
  .back-link:hover {{ color: var(--gold); }}
  .container {{ max-width: 900px; margin: 0 auto; padding: 0 1.5rem 4rem; }}
  .intro-box {{ background: var(--cream-dark); border-left: 4px solid var(--gold); padding: 1.4rem 1.6rem; margin: 2.5rem 0; font-family: 'EB Garamond', serif; font-size: 1.08rem; font-style: italic; color: var(--ink-light); border-radius: 0 4px 4px 0; }}
  .toc {{ display: flex; flex-wrap: wrap; gap: 0.45rem; margin: -1rem 0 2rem; }}
  .toc a {{ font-family: 'IBM Plex Mono', monospace; font-size: 0.68rem; color: var(--ink-faint); border: 1px solid var(--border-light); background: rgba(255,255,255,0.55); border-radius: 999px; padding: 0.24rem 0.55rem; text-decoration: none; }}
  .toc a:hover {{ color: var(--accent); border-color: var(--border); }}
  .status {{ background: rgba(255,255,255,0.55); border: 1px solid var(--border-light); border-radius: 6px; color: var(--ink-faint); font-family: 'IBM Plex Mono', monospace; font-size: 0.78rem; margin: 2rem 0; padding: 1rem; }}
  .exercise-card {{ background: white; border: 1px solid var(--border); border-radius: 6px; margin-top: 2rem; overflow: hidden; box-shadow: 0 2px 8px var(--shadow); }}
  .exercise-header {{ display: flex; align-items: center; gap: 1rem; padding: 1rem 1.4rem; background: var(--ink); color: var(--cream); }}
  .exercise-badge {{ font-family: 'IBM Plex Mono', monospace; font-size: 0.7rem; background: var(--accent); color: white; padding: 0.2rem 0.6rem; border-radius: 3px; white-space: nowrap; letter-spacing: 0.05em; }}
  .exercise-badge.medium {{ background: var(--accent-warm); }}
  .exercise-badge.hard {{ background: var(--blue-muted); }}
  .exercise-title {{ font-family: 'EB Garamond', serif; font-size: 1.12rem; font-weight: 500; flex: 1; }}
  .exercise-problem {{ padding: 1.4rem 1.6rem 0; }}
  .problem-text {{ font-family: 'EB Garamond', serif; font-size: 1.05rem; color: var(--ink); line-height: 1.75; }}
  .schema-wrap {{ margin: 1.2rem 0 0; background: var(--cream-dark); border: 1px solid var(--border); border-radius: 4px; padding: 1rem; text-align: center; }}
  .schema-wrap .schema-caption {{ font-family: 'IBM Plex Mono', monospace; font-size: 0.7rem; color: var(--ink-faint); margin-top: 0.5rem; text-transform: uppercase; letter-spacing: 0.08em; }}
  svg, canvas, img {{ max-width: 100%; height: auto; }}
  .solution-toggle {{ display: flex; align-items: center; gap: 0.7rem; width: 100%; padding: 0.85rem 1.6rem; cursor: pointer; user-select: none; border: 0; border-top: 1px solid var(--border-light); margin-top: 1.2rem; color: var(--accent); background: transparent; font-family: 'IBM Plex Mono', monospace; font-size: 0.75rem; letter-spacing: 0.1em; text-transform: uppercase; transition: background 0.15s; text-align: left; }}
  .solution-toggle:hover {{ background: var(--cream); }}
  .solution-toggle .sol-icon {{ display: inline-block; width: 1rem; font-size: 0.9rem; transition: transform 0.3s; }}
  .exercise-card.open .solution-toggle .sol-icon {{ transform: rotate(180deg); }}
  .exercise-solution {{ display: none; padding: 0 1.6rem 1.4rem; border-top: 1px dashed var(--border-light); }}
  .exercise-card.open .exercise-solution {{ display: block; }}
  .solution-divider {{ display: flex; align-items: center; gap: 0.8rem; margin: 1.2rem 0 1rem; }}
  .solution-divider span {{ font-family: 'IBM Plex Mono', monospace; font-size: 0.72rem; color: var(--accent); text-transform: uppercase; letter-spacing: 0.12em; white-space: nowrap; }}
  .solution-divider::before, .solution-divider::after {{ content: ''; flex: 1; height: 1px; background: var(--border); }}
  .step {{ margin: 1rem 0; padding-left: 1rem; border-left: 3px solid var(--border-light); }}
  .step-label {{ font-family: 'IBM Plex Mono', monospace; font-size: 0.68rem; color: var(--ink-faint); text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 0.3rem; }}
  .step p {{ font-size: 0.95rem; color: var(--ink-light); line-height: 1.65; }}
  .step .math-block {{ margin: 0.6rem 0; }}
  .result-box {{ background: linear-gradient(135deg, var(--ink) 0%, #2d2420 100%); color: var(--cream); border-radius: 5px; padding: 1rem 1.4rem; margin-top: 1.4rem; display: flex; align-items: center; gap: 1rem; flex-wrap: wrap; }}
  .result-box .res-label {{ font-family: 'IBM Plex Mono', monospace; font-size: 0.65rem; color: var(--gold); text-transform: uppercase; letter-spacing: 0.12em; white-space: nowrap; }}
  .result-box .res-value {{ font-family: 'EB Garamond', serif; font-size: 1.1rem; }}
  .concept-note {{ background: #f0f5f0; border-left: 3px solid var(--green-muted); padding: 0.8rem 1.1rem; margin-top: 1.2rem; border-radius: 0 4px 4px 0; font-size: 0.9rem; color: var(--ink-light); }}
  .concept-note .cn-label {{ font-family: 'IBM Plex Mono', monospace; font-size: 0.65rem; color: var(--green-muted); text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 0.3rem; }}
  .warning-band {{ background: var(--blue-muted); color: white; padding: 0.28rem 1rem; font-family: 'IBM Plex Mono', monospace; font-size: 0.65rem; letter-spacing: 0.08em; text-transform: uppercase; }}
  details {{ border: 1px solid var(--border-light); border-radius: 4px; margin-top: 1rem; overflow: hidden; }}
  summary {{ cursor: pointer; padding: 0.85rem 1rem; color: var(--accent); font-family: 'IBM Plex Mono', monospace; font-size: 0.75rem; letter-spacing: 0.08em; text-transform: uppercase; }}
  footer {{ text-align: center; padding: 2rem; font-family: 'EB Garamond', serif; font-size: 1rem; font-style: italic; color: var(--ink-faint); border-top: 1px solid var(--border-light); margin-top: 4rem; }}
  .katex-display {{ margin: 0.7rem 0 !important; }}
  @media (max-width: 600px) {{
    .site-header h1 {{ font-size: 2rem; }}
    .exercise-header {{ align-items: flex-start; flex-direction: column; gap: 0.45rem; }}
  }}
</style>
<script>
  window.EXERCISES_JSON = {js_string(json_name)};
</script>
</head>
<body>
<header class="site-header">
  <a class="back-link" href="{escape(back_link, quote=True)}">Torna al catalogo</a>
  <h1>{html_text(title)}</h1>
  <p class="subtitle">{subtitle}</p>
  <div class="meta-row"><span>{count} esercizi svolti</span><span>&middot;</span><span>testo sempre visibile</span><span>&middot;</span><span>soluzione espandibile</span></div>
</header>

<div class="container">
  <div class="intro-box">{html_text(description)}</div>
  <nav class="toc" id="exercise-toc" aria-label="Elenco esercizi"></nav>
  <div id="exercises-root" class="exercise-list">
    <p class="status">Caricamento esercizi...</p>
  </div>
</div>

<footer>{html_text(title)} &middot; Esercizi svolti</footer>

<script>
const MATH_DELIMITERS = [
  {{ left: "$$", right: "$$", display: true }},
  {{ left: "$", right: "$", display: false }},
  {{ left: "\\\\[", right: "\\\\]", display: true }},
  {{ left: "\\\\(", right: "\\\\)", display: false }}
];

function escapeHTML(value) {{
  return String(value ?? "").replace(/[&<>"']/g, char => ({{
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;"
  }}[char]));
}}

function levelLabel(exercise) {{
  const raw = String(exercise.level || exercise.difficulty || exercise.difficolta || "Esercizio");
  const normalized = raw.toLowerCase();
  let className = "";
  if (normalized.includes("intermedio") || normalized.includes("medio")) className = " medium";
  if (normalized.includes("avanzato") || normalized.includes("difficile") || normalized.includes("hard")) className = " hard";
  const label = raw === "base" ? "Base" : raw.charAt(0).toUpperCase() + raw.slice(1);
  return {{ label, className }};
}}

function exerciseFile(exercise) {{
  return exercise.file || exercise.source || exercise.href || "";
}}

function setToggleState(card, isOpen) {{
  card.classList.toggle("open", isOpen);
  const button = card.querySelector(".solution-toggle");
  if (!button) return;
  const icon = button.querySelector(".sol-icon");
  const label = button.querySelector(".solution-label");
  if (icon) icon.textContent = isOpen ? "-" : "+";
  if (label) label.textContent = isOpen ? "Nascondi soluzione" : "Mostra soluzione";
  button.setAttribute("aria-expanded", String(isOpen));
}}

function toggleSolution(button) {{
  const card = button.closest(".exercise-card");
  if (!card) return;
  setToggleState(card, !card.classList.contains("open"));
}}

window.toggleSol = toggleSolution;

document.addEventListener("click", event => {{
  const button = event.target.closest(".solution-toggle");
  if (!button) return;
  event.preventDefault();
  toggleSolution(button);
}});

function renderMath(container) {{
  if (window.renderMathInElement) {{
    window.renderMathInElement(container, {{ delimiters: MATH_DELIMITERS, throwOnError: false }});
  }}
  if (window.MathJax && window.MathJax.typesetPromise) {{
    window.MathJax.typesetPromise([container]);
  }}
}}

function createToggle() {{
  const button = document.createElement("button");
  button.type = "button";
  button.className = "solution-toggle";
  button.setAttribute("aria-expanded", "false");
  button.innerHTML = '<span class="sol-icon">+</span><span class="solution-label">Mostra soluzione</span>';
  return button;
}}

function createCard(exercise, index, problemHTML, solutionHTML) {{
  const card = document.createElement("article");
  card.className = "exercise-card";
  card.id = `exercise-${{index + 1}}`;
  card.dataset.source = exerciseFile(exercise);

  const level = levelLabel(exercise);
  const title = exercise.title || exerciseFile(exercise) || `Esercizio ${{index + 1}}`;

  card.innerHTML = `
    <div class="exercise-header">
      <span class="exercise-badge${{level.className}}">${{escapeHTML(level.label)}}</span>
      <span class="exercise-title">${{escapeHTML(title)}}</span>
    </div>
    <div class="exercise-problem">
      <div class="problem-text">${{problemHTML || "<p>Testo esercizio non disponibile.</p>"}}</div>
    </div>
  `;

  if (solutionHTML && solutionHTML.trim()) {{
    card.appendChild(createToggle());
    const solution = document.createElement("div");
    solution.className = "exercise-solution";
    solution.innerHTML = `<div class="solution-divider"><span>Soluzione</span></div>${{solutionHTML}}`;
    card.appendChild(solution);
    setToggleState(card, false);
  }}

  return card;
}}

function removeUnsafeNodes(root) {{
  root.querySelectorAll("script, style, link, meta, title").forEach(node => node.remove());
  root.querySelectorAll(".solution-toggle").forEach(node => node.removeAttribute("onclick"));
}}

function normalizeToggleElement(card) {{
  const current = card.querySelector(".solution-toggle");
  if (!current) return null;

  if (current.tagName.toLowerCase() === "button") {{
    current.type = "button";
    return current;
  }}

  const button = createToggle();
  current.replaceWith(button);
  return button;
}}

function normalizeExistingCard(card, exercise, index) {{
  removeUnsafeNodes(card);
  card.classList.add("exercise-card");
  card.id = `exercise-${{index + 1}}`;
  card.dataset.source = exerciseFile(exercise);
  card.classList.remove("open");

  if (!card.querySelector(".exercise-header")) {{
    const level = levelLabel(exercise);
    const header = document.createElement("div");
    header.className = "exercise-header";
    header.innerHTML = `
      <span class="exercise-badge${{level.className}}">${{escapeHTML(level.label)}}</span>
      <span class="exercise-title">${{escapeHTML(exercise.title || exerciseFile(exercise))}}</span>
    `;
    card.prepend(header);
  }}

  if (card.querySelector(".exercise-solution") && !card.querySelector(".solution-toggle")) {{
    const solution = card.querySelector(".exercise-solution");
    card.insertBefore(createToggle(), solution);
  }} else {{
    normalizeToggleElement(card);
  }}

  setToggleState(card, false);
  return card;
}}

function convertDetailsCard(source, exercise, index) {{
  const clone = source.cloneNode(true);
  removeUnsafeNodes(clone);

  const details = clone.querySelector("details");
  let solutionHTML = "";
  if (details) {{
    const solution = details.cloneNode(true);
    const summary = solution.querySelector("summary");
    if (summary) summary.remove();
    solutionHTML = solution.innerHTML;
    details.remove();
  }}

  const body = clone.querySelector(".exercise-body") || clone;
  const problem = body.cloneNode(true);
  problem.querySelectorAll("details").forEach(node => node.remove());

  return createCard(exercise, index, problem.innerHTML, solutionHTML);
}}

function extractFromDocument(doc, exercise, index) {{
  const statement = doc.querySelector("template[data-exercise-statement]");
  const solution = doc.querySelector("template[data-exercise-solution]");
  if (statement || solution) {{
    return createCard(
      exercise,
      index,
      statement ? statement.innerHTML : "",
      solution ? solution.innerHTML : ""
    );
  }}

  const existingCard = doc.querySelector("article.exercise-card, .exercise-card");
  if (existingCard) {{
    if (existingCard.querySelector(".exercise-solution") || existingCard.querySelector(".solution-toggle")) {{
      return normalizeExistingCard(existingCard.cloneNode(true), exercise, index);
    }}
    if (existingCard.querySelector("details")) {{
      return convertDetailsCard(existingCard, exercise, index);
    }}
    return normalizeExistingCard(existingCard.cloneNode(true), exercise, index);
  }}

  const article = doc.querySelector("article.exercise, .exercise");
  if (article) {{
    const clone = article.cloneNode(true);
    if (clone.querySelector("details")) {{
      return convertDetailsCard(clone, exercise, index);
    }}
    return createCard(exercise, index, clone.innerHTML, "");
  }}

  const body = doc.body ? doc.body.cloneNode(true) : document.createElement("div");
  removeUnsafeNodes(body);
  body.querySelectorAll("template").forEach(node => node.remove());
  return createCard(exercise, index, body.innerHTML, "");
}}

async function loadExercise(exercise, index) {{
  const file = exerciseFile(exercise);
  if (!file) {{
    return createCard(exercise, index, "<p>File esercizio non indicato nel JSON.</p>", "");
  }}

  try {{
    const response = await fetch(file);
    if (!response.ok) throw new Error(`${{response.status}} ${{response.statusText}}`);
    const html = await response.text();
    const doc = new DOMParser().parseFromString(html, "text/html");
    return extractFromDocument(doc, exercise, index);
  }} catch (error) {{
    return createCard(
      exercise,
      index,
      `<p>Impossibile caricare <code>${{escapeHTML(file)}}</code>: ${{escapeHTML(error.message)}}</p>`,
      ""
    );
  }}
}}

function renderTOC(exercises) {{
  const toc = document.getElementById("exercise-toc");
  toc.innerHTML = "";
  exercises.forEach((exercise, index) => {{
    const link = document.createElement("a");
    link.href = `#exercise-${{index + 1}}`;
    link.textContent = `${{index + 1}}. ${{exercise.title || exerciseFile(exercise)}}`;
    toc.appendChild(link);
  }});
}}

async function renderCollection() {{
  const root = document.getElementById("exercises-root");

  try {{
    const response = await fetch(window.EXERCISES_JSON);
    if (!response.ok) throw new Error(`${{response.status}} ${{response.statusText}}`);
    const manifest = await response.json();
    const exercises = Array.isArray(manifest.exercises) ? manifest.exercises : [];

    renderTOC(exercises);
    root.innerHTML = "";

    if (!exercises.length) {{
      root.innerHTML = '<p class="status">Nessun esercizio trovato nel manifest.</p>';
      return;
    }}

    for (const [index, exercise] of exercises.entries()) {{
      const card = await loadExercise(exercise, index);
      root.appendChild(card);
      renderMath(card);
    }}
  }} catch (error) {{
    root.innerHTML = `<p class="status"><strong>Errore:</strong> ${{escapeHTML(error.message)}}</p>`;
  }}
}}

document.addEventListener("DOMContentLoaded", renderCollection);
</script>
</body>
</html>
"""


def load_existing_root_catalog(site_root: Path) -> dict[str, Any]:
    catalog_path = site_root / GLOBAL_CATALOG_NAME
    return load_json(catalog_path) or {}


def catalog_category_key(subject: str, category: str) -> str:
    return f"{subject.casefold()}::{category.casefold()}"


def existing_category_lookup(site_root: Path) -> dict[str, dict[str, Any]]:
    catalog = load_existing_root_catalog(site_root)
    lookup: dict[str, dict[str, Any]] = {}

    for category in catalog.get("categories") or []:
        if not isinstance(category, dict):
            continue
        name = str(category.get("name") or "").strip()
        if not name:
            continue
        subject = str(category.get("subject") or infer_subject_from_category_name(name) or "Fisica").strip()
        lookup[catalog_category_key(subject, name)] = category

    return lookup


def infer_subject_from_category_name(category_name: str) -> str:
    math_names = {
        "algebra",
        "analisi",
        "geometria",
        "geometria analitica",
        "limiti",
        "trigonometria",
        "probabilita",
        "probabilita e statistica",
        "statistica",
    }
    normalized = (
        category_name.casefold()
        .replace("à", "a")
        .replace("è", "e")
        .replace("é", "e")
        .replace("ì", "i")
        .replace("ò", "o")
        .replace("ù", "u")
    )
    return "Matematica" if normalized in math_names else "Fisica"


def iter_collection_manifests(site_root: Path) -> list[Path]:
    manifests: list[Path] = []

    for subject_slug in sorted(ALLOWED_ROOTS):
        subject_dir = site_root / subject_slug
        if not subject_dir.exists():
            continue

        for path in sorted(subject_dir.rglob("*.json"), key=lambda item: natural_key(item.relative_to(site_root).as_posix())):
            if path.name.casefold() == "collection.json":
                continue
            if is_exercise_manifest(path):
                manifests.append(path)

    return manifests


def collection_entry_from_manifest(site_root: Path, manifest_path: Path, index: int) -> dict[str, Any] | None:
    manifest = load_json(manifest_path)
    if not manifest:
        return None

    rel_dir = PurePosixPath(manifest_path.parent.relative_to(site_root).as_posix())
    parts = rel_dir.parts
    if not parts or parts[0] not in ALLOWED_ROOTS:
        return None

    exercises = manifest.get("exercises") if isinstance(manifest.get("exercises"), list) else []
    if not exercises:
        return None

    inferred = infer_path_metadata(rel_dir)
    subject_info = SUBJECTS.get(parts[0], {})
    title = str(manifest.get("title") or inferred["title"])
    subject = str(manifest.get("subject") or subject_info.get("name") or inferred["subject"])
    category = str(manifest.get("category") or inferred["category"] or subject)
    topic = str(manifest.get("topic") or inferred["topic"] or title)
    description = str(
        manifest.get("description")
        or f"Raccolta con {len(exercises)} esercizi svolti."
    )
    order = normalize_order(manifest.get("order"))
    if order is None:
        order = (index + 1) * 10

    return {
        "id": rel_dir.as_posix().replace("/", "-"),
        "title": title,
        "description": description,
        "subject": subject,
        "category": category,
        "topic": topic,
        "icon": manifest.get("icon") or "",
        "order": order,
        "tags": unique_list([manifest.get("tags"), *(exercise.get("tags") for exercise in exercises)], limit=12),
        "level": manifest.get("level") or "",
        "schoolYear": manifest.get("schoolYear") or "",
        "estimatedTime": manifest.get("estimatedTime") or f"{len(exercises)} esercizi",
        "file": f"{rel_dir.as_posix()}/index.html",
        "manifest": f"{rel_dir.as_posix()}/{manifest_path.name}",
        "count": len(exercises),
        "isCollection": True,
        "isWip": bool(manifest.get("isWip", False)),
    }


def build_global_catalog(site_root: Path) -> dict[str, Any]:
    entries = [
        entry
        for index, manifest_path in enumerate(iter_collection_manifests(site_root))
        if (entry := collection_entry_from_manifest(site_root, manifest_path, index)) is not None
    ]

    subject_order = {info["name"]: info["order"] for info in SUBJECTS.values()}
    entries.sort(
        key=lambda entry: (
            subject_order.get(entry["subject"], 999999),
            entry["category"].casefold(),
            normalize_order(entry.get("order")) or 999999,
            entry["topic"].casefold(),
            entry["title"].casefold(),
        )
    )

    category_lookup = existing_category_lookup(site_root)
    categories_by_key: dict[str, dict[str, Any]] = {}

    for index, entry in enumerate(entries):
        key = catalog_category_key(entry["subject"], entry["category"])
        if key in categories_by_key:
            continue

        existing = category_lookup.get(key, {})
        subject_slug = entry["subject"].casefold()
        subject_color = next(
            (info["color"] for info in SUBJECTS.values() if info["name"].casefold() == subject_slug),
            "#365f85",
        )

        categories_by_key[key] = {
            "name": entry["category"],
            "subject": entry["subject"],
            "order": normalize_order(existing.get("order")) or (index + 1) * 10,
            "color": existing.get("color") or subject_color,
            "description": existing.get("description") or f"Raccolte di {entry['category'].lower()}.",
        }

    categories = sorted(
        categories_by_key.values(),
        key=lambda category: (
            subject_order.get(category["subject"], 999999),
            normalize_order(category.get("order")) or 999999,
            category["name"].casefold(),
        ),
    )

    return {
        "catalogGenerator": "generate_exercises.py",
        "subjects": list(SUBJECTS.values()),
        "categories": categories,
        "exercises": entries,
    }


def update_global_catalog(site_root: Path) -> Path:
    catalog_path = site_root / GLOBAL_CATALOG_NAME
    catalog = build_global_catalog(site_root)
    changed = write_text_if_changed(catalog_path, json_dump(catalog))
    print(f"[OK] Catalogo globale {'aggiornato' if changed else 'gia aggiornato'}: {catalog_path}")
    print(f"[OK] Raccolte nel catalogo: {len(catalog['exercises'])}")
    return catalog_path


def write_outputs(manifest_path: Path, manifest: dict[str, Any], category_rel: PurePosixPath) -> None:
    json_content = json_dump(manifest)
    json_changed = write_text_if_changed(manifest_path, json_content)

    index_path = manifest_path.parent / "index.html"
    index_content = build_index_html(manifest, manifest_path.name, category_rel)
    index_changed = write_text_if_changed(index_path, index_content)

    print(f"[OK] JSON {'aggiornato' if json_changed else 'gia aggiornato'}: {manifest_path}")
    print(f"[OK] index.html {'aggiornato' if index_changed else 'gia aggiornato'}: {index_path}")


def print_summary(manifest: dict[str, Any]) -> None:
    exercises = manifest.get("exercises") or []
    print(f"[OK] Esercizi trovati: {len(exercises)}")
    for exercise in exercises:
        order = exercise.get("order")
        title = exercise.get("title") or "Senza titolo"
        file = exercise.get("file") or exercise.get("source") or "?"
        print(f"  - {order} | {title} | {file}")


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Genera o aggiorna il manifest JSON e l'index di una sottocategoria.",
        epilog=(
            "Esempi:\n"
            "  python generate_exercises.py fisica/meccanica/dinamica\n"
            "  python generate_exercises.py fisica/elettrostatica/coulomb\n"
            "  python generate_exercises.py matematica/limiti/forme-indeterminate"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        "path",
        nargs="?",
        help="Percorso relativo, per esempio fisica/meccanica/dinamica",
    )
    parser.add_argument(
        "--input",
        dest="input_dir",
        help="Percorso relativo equivalente all'argomento diretto",
    )
    parser.add_argument(
        "--json",
        dest="json_name",
        default=None,
        help="Nome del JSON nella sottocategoria (se omesso riusa quello esistente o exercises.json)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Interrompe la generazione se un esercizio non ha metadati validi",
    )
    parser.add_argument(
        "--write-index",
        action="store_true",
        help="Compatibilita': l'index viene aggiornato automaticamente anche senza questa opzione",
    )

    return parser


def main() -> int:
    parser = make_parser()
    args = parser.parse_args()
    raw_target = args.input_dir or args.path

    if not raw_target:
        parser.print_help(sys.stderr)
        return 2

    try:
        category_rel = normalize_target(raw_target)
        site_root = Path(__file__).resolve().parent
        target_dir = (site_root / Path(*category_rel.parts)).resolve()
        root_resolved = site_root.resolve()

        try:
            target_dir.relative_to(root_resolved)
        except ValueError as exc:
            raise ValueError("Il percorso deve restare dentro la root del sito.") from exc

        if not target_dir.exists():
            raise FileNotFoundError(f"La directory non esiste: {target_dir}")
        if not target_dir.is_dir():
            raise NotADirectoryError(f"Il percorso indicato non e' una directory: {target_dir}")

        collection_config = load_collection_config(target_dir)
        manifest_path = find_manifest_path(target_dir, args.json_name)
        source_dir = resolve_source_dir(target_dir, collection_config, manifest_path)

        print(f"[INFO] Root sito: {site_root}")
        print(f"[INFO] Categoria: {category_rel.as_posix()}")
        print(f"[INFO] Cartella esercizi: {source_dir}")
        print(f"[INFO] Manifest JSON: {manifest_path.name}")

        manifest = build_manifest(
            target_dir=target_dir,
            source_dir=source_dir,
            category_rel=category_rel,
            manifest_path=manifest_path,
            collection_config=collection_config,
            strict=args.strict,
        )

        write_outputs(manifest_path, manifest, category_rel)
        update_global_catalog(site_root)
        print_summary(manifest)
        return 0

    except Exception as exc:
        print(f"[ERRORE] {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
